font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13

window_margin_width 15

foreground #dddddd
background #282a2e

background_opacity 0.8

map ctrl+shift+equal change_font_size all +2.0
map ctrl+shift+plus change_font_size all +2.0
map ctrl+shift+kp_add change_font_size all +2.0
map cmd+plus change_font_size all +2.0 🍎
map cmd+equal change_font_size all +2.0 🍎
map shift+cmd+equal change_font_size all +2.0 🍎
